# Generated by Django 4.0.4 on 2022-04-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justSaid_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
