# Generated by Django 4.0.4 on 2022-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justSaid_web', '0002_rename_auther_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='justSaid', max_length=255),
        ),
    ]
